# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
print("The diameter of {} is {} Kilometers. ".format(planet,diameter))

The diameter of Earth is 12742 Kilometers. 


## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
n1= np.zeros(10)
print(n1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
n1 = np.ones(10)*5
print(n1)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [10]:
n1 = np.arange(20,35,2)
print(n1)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
n1 = np.arange(0,9).reshape((3,3))
n1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
a = np.array([1,2,3])
b = np.array([4,5,6])

n2= np.concatenate((a,b),axis =0)
n2

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [13]:
import pandas as pd
peoples = [ ('jon', 'Apples') ,
             ('Reeta', 'Mangos') ,
             ('Aasha', 'Grapes') ]
df = pd.DataFrame(peoples, columns = ['Name' , 'Product'])
df

Name Product
0    jon  Apples
1  Reeta  Mangos
2  Aasha  Grapes

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [14]:
import pandas as pd
import numpy as np
data = np.array(['Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023',
'Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','Jan 2023','feb 2023','feb 2023','feb 2023','feb 2023','feb 2023','feb 2023','feb 2023','feb 2023','feb 2023','feb 2023'])
s = pd.Series(data,index=['1st','2nd','3rd','4th','5th','6th','7th','8th','9th','10th','11th','12th','13th','14th','15th','16th','17th','18th','19th','20th','21st','22nd','23rd','24th','25th','26th','27th','28th','29th','30th','31st','1st','2nd','3rd','4th','5th','6th','7th','8th','9th','10th'])
print(s)

1st     Jan 2023
2nd     Jan 2023
3rd     Jan 2023
4th     Jan 2023
5th     Jan 2023
6th     Jan 2023
7th     Jan 2023
8th     Jan 2023
9th     Jan 2023
10th    Jan 2023
11th    Jan 2023
12th    Jan 2023
13th    Jan 2023
14th    Jan 2023
15th    Jan 2023
16th    Jan 2023
17th    Jan 2023
18th    Jan 2023
19th    Jan 2023
20th    Jan 2023
21st    Jan 2023
22nd    Jan 2023
23rd    Jan 2023
24th    Jan 2023
25th    Jan 2023
26th    Jan 2023
27th    Jan 2023
28th    Jan 2023
29th    Jan 2023
30th    Jan 2023
31st    Jan 2023
1st     feb 2023
2nd     feb 2023
3rd     feb 2023
4th     feb 2023
5th     feb 2023
6th     feb 2023
7th     feb 2023
8th     feb 2023
9th     feb 2023
10th    feb 2023
dtype: object


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [15]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns =['no', 'student','age'])
print(df )

   no student  age
0   1     aaa   22
1   2     bbb   25
2   3     ccc   24
